name: Build

on:
  workflow_call:
  push:
    branches:
      - main
      - master
      - release-*
  pull_request:
    branches:
      - main
      - master
      - release-*
  merge_group:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  QEMU_VERSION: 7.0.0-7

jobs:
  build-multi-arch:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    # Run steps on a matrix of 2 arch.
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the builder image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.builder
          push: false
          load: true
          platforms: linux/${{ matrix.arch }}
          tags: perf-map-agent-builder:latest

      - name: "Run Builder ${{ matrix.arch }}"
        run: |
          # Run platform specific based builder image. Run it as a daemon in the background.
          # Sleep the container for 1 day so that it keeps running until
          # other steps are completed and the steps below can use the same container.
          docker run \
            --name=builder \
            --detach \
            --platform 'linux/${{ matrix.arch }}' \
            --volume /home/runner/work:/home/runner/work \
            --workdir "${PWD}" \
            docker.io/library/perf-map-agent-builder:latest \
            bash -c 'uname -m && sleep 1d'

      - name: "Build ${{ matrix.arch }}"
        shell: docker exec builder bash -e {0}
        run: |
          cmake .
          make

      - name: Upload generated artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: perf-map-agent-${{ matrix.arch }}
          if-no-files-found: error
          path: out/
