name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  discussions: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3.0.2
        with:
          name: perf-map-agent-amd64
          path: out/amd64

      - uses: actions/download-artifact@v3.0.2
        with:
          name: perf-map-agent-arm64
          path: out/arm64

      - name: archive
        run: |
          echo "Archive"
          ls -al ./out
          tar -czvf perf-map-agent-x86_64.tar.gz ./out/amd64
          tar -czvf perf-map-agent-aarch64.tar.gz ./out/arm64

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            perf-map-agent-x86_64.tar.gz
            perf-map-agent-aarch64.tar.gz
          fail_on_unmatched_files: true
          discussion_category_name: "Release"
          generate_release_notes: true
          draft: false
          prerelease: false
